// swift-tools-version:5.9
import PackageDescription

// Host package used for *logic-only* unit tests (runs on macOS and Linux CI).
// The iOS app itself is built from the Xcode project generated by `project.yml`.
// Everything under Sources/Core is platform agnostic: no Metal, no UIKit, no simd.
let package = Package(
    name: "SteelFrontCore",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "SteelFrontCore", targets: ["Core"]),
    ],
    targets: [
        .target(name: "Core", path: "Sources/Core"),
        .testTarget(name: "CoreTests", dependencies: ["Core"], path: "Tests/CoreTests"),
    ]
)
